// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      stores: {
        Row: {
          id: string
          shop_domain: string
          access_token: string
          shop_name: string
          email: string
          owner_id: string
          plan: string
          created_at: string
          updated_at: string
          is_active: boolean
          settings: Json
        }
        Insert: Omit<Database['public']['Tables']['stores']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['stores']['Insert']>
      }
      products: {
        Row: {
          id: string
          store_id: string
          shopify_product_id: string
          title: string
          handle: string
          product_type: string
          vendor: string
          tags: string[]
          status: string
          created_at: string
          updated_at: string
          synced_at: string
          data: Json
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      ai_analyses: {
        Row: {
          id: string
          store_id: string
          product_id: string | null
          analysis_type: string
          status: 'pending' | 'processing' | 'completed' | 'failed'
          result: Json
          error: string | null
          created_at: string
          completed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['ai_analyses']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['ai_analyses']['Insert']>
      }
      analytics_snapshots: {
        Row: {
          id: string
          store_id: string
          date: string
          revenue: number
          orders_count: number
          average_order_value: number
          conversion_rate: number
          unique_visitors: number
          page_views: number
          top_products: Json
          traffic_sources: Json
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['analytics_snapshots']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['analytics_snapshots']['Insert']>
      }
      webhook_logs: {
        Row: {
          id: string
          store_id: string
          topic: string
          payload: Json
          processed_at: string
          status: 'success' | 'failed'
          error: string | null
        }
        Insert: Omit<Database['public']['Tables']['webhook_logs']['Row'], 'id' | 'processed_at'>
        Update: Partial<Database['public']['Tables']['webhook_logs']['Insert']>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}